export let data = [
    {
        title: "Bharti Musalmanon Ko Dhamkiyan | Hasb e Haal | Dunya News",
        youtube_url: "https://www.youtube.com/watch?v=9CCTPgHC8NU",
        thumbnail: "https://i.ytimg.com/vi/9CCTPgHC8NU/maxresdefault.jpg",
        details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages",
        channel: "https://www.youtube.com/channel/UCnMBV5Iw4WqKILKue1nP6Hg",
        channel_name: "Dunya News",
        tags: "Musalman, Dhamki, Bharti"
    },
    {
        title: "Suspicious Transactions: Shehbaz Sharif's Family Under Severe Charges Of Money Laundering",
        youtube_url: 'https://www.youtube.com/watch?v=VDgst3v0bxM&list=PL77NPbvlfztaqiSISvGMh96eB-hKFim_x',
        thumbnail: 'https://www.geo.tv/assets/uploads/updates/2019-04-16/video_thumb_image_433353.jpg',
        details: "Aaj Shahzaib Khanzada Kay Sath - Suspicious Transactions: Shehbaz Sharif&s Family Under Severe Charges Of Money Launderin",
        tags: "#ASKK #SulemanShehbaz #NAB",
        channel: "https://www.youtube.com/channel/UCnMBV5Iw4WqKILKue1nP6Hg",
        channel_name: "Geo News",
    },
    {
        title: "Suspicious Transactions: Shehbaz Sharif's Family Under Severe Charges Of Money Laundering",
        youtube_url: 'https://www.youtube.com/watch?v=VDgst3v0bxM&list=PL77NPbvlfztaqiSISvGMh96eB-hKFim_x',
        thumbnail: 'https://www.geo.tv/assets/uploads/updates/2019-04-16/video_thumb_image_433353.jpg',
        details: "Aaj Shahzaib Khanzada Kay Sath - Suspicious Transactions: Shehbaz Sharif&s Family Under Severe Charges Of Money Launderin",
        tags: "#ASKK #SulemanShehbaz #NAB",
        channel: "https://www.youtube.com/channel/UCnMBV5Iw4WqKILKue1nP6Hg",
        channel_name: "Geo News",
    },
    {
        title: "Suspicious Transactions: Shehbaz Sharif's Family Under Severe Charges Of Money Laundering",
        youtube_url: 'https://www.youtube.com/watch?v=VDgst3v0bxM&list=PL77NPbvlfztaqiSISvGMh96eB-hKFim_x',
        thumbnail: 'https://www.geo.tv/assets/uploads/updates/2019-04-16/video_thumb_image_433353.jpg',
        details: "Aaj Shahzaib Khanzada Kay Sath - Suspicious Transactions: Shehbaz Sharif&s Family Under Severe Charges Of Money Launderin",
        tags: "#ASKK #SulemanShehbaz #NAB",
        channel: "https://www.youtube.com/channel/UCnMBV5Iw4WqKILKue1nP6Hg",
        channel_name: "Geo News",
    },
    {
        title: "Suspicious Transactions: Shehbaz Sharif's Family Under Severe Charges Of Money Laundering",
        youtube_url: 'https://www.youtube.com/watch?v=VDgst3v0bxM&list=PL77NPbvlfztaqiSISvGMh96eB-hKFim_x',
        thumbnail: 'https://www.geo.tv/assets/uploads/updates/2019-04-16/video_thumb_image_433353.jpg',
        details: "Aaj Shahzaib Khanzada Kay Sath - Suspicious Transactions: Shehbaz Sharif&s Family Under Severe Charges Of Money Launderin",
        tags: "#ASKK #SulemanShehbaz #NAB",
        channel: "https://www.youtube.com/channel/UCnMBV5Iw4WqKILKue1nP6Hg",
        channel_name: "Geo News",
    },
]